apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: k8s-poc-stateless-app
        image: jcarabantes/k8s-poc-stateless-app:latest
        ports:
        - containerPort: 8081
